version: '3.5'
services:

  sonarqube:
    hostname: sonarqube
    image: sonarqube:latest
    container_name: SONAR
    restart: always
    ports:
      - "9002:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
    networks:
      services-network-01:
        aliases:
          - sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  
networks:
  services-network-01:
    name: services-network-01
    driver: bridge